addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.4.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.1.20")
addSbtPlugin("com.codecommit"            % "sbt-github-actions" % "0.13.0")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"     % "1.5.10")
addSbtPlugin("com.timushev.sbt"          % "sbt-rewarn"         % "0.1.3")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.7.0")
